# The syntax is key = value, comments start with ‘#’
# This configuration file allows for the following options:

# max_vocabulary_size - The maximum number of token pairs generated in
# training. The actually vocabulary size in the tokenizer model will be
# max_vocabulary_size + 255 + the length of special_tokens.
# Value must be a number which is greater than 0
max_vocabulary_size = 100000

# pre_tokenizer_pattern - The regular pattern for the tokenizer model to
# split the corpus into parts and apply the BPE algorithm on these parts.
# Value must be a valid regular pattern.
# This option is optional. Default value is
# '(?:[sdmt]|ll|ve|re)| ?\p{L}++| ?\p{N}++| ?[^\s\p{L}\p{N}]++|\s++$|\s+(?!\S)|\s
#pre_tokenizer_pattern

# special_tokens - The strings for the tokenizer model to recognize as
# special tokens. Value must be multiple strings separated by comma.
# This option is optional. Default value is empty.
special_tokens = <|beginoftext|>, <|middleoftext|>, <|endoftext|>

# train_path - The corpus path for the tokenizer model to train.
# Value must be a valid file path.
train_path = examples/bpe-wiki.txt

# verbose - Show information verbosely in training.
# This option is optional and there is no value for this option;
# just the presence of the option activates it.
#verbose

# save_path - The path where the tokenizer model is saved after training.
# Value must be a valid file path.
save_path = models/example.bin

# report_interval - The episode interval for reporting in training.
# Value must be a integer which is greater than zero.
report_interval = 100

# jobs - The number of paraller threads. Value must be a integer which is
# greater than zero. Any value that is greater than the maximum amount
# of parallelism available for this program will be restricted to the
# maximum value.
# This option is optional. Default value is 1, meaning single thread.
jobs = 8
